version: "3.9"

services:
  web:
    build: .
    container_name: juegomichi_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=juegomichi.settings
    depends_on:
      - db
    networks:
      - michi_net

  db:
    image: mysql:8.0
    container_name: juegomichi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: juego_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - michi_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: juegomichi_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=1234
    depends_on:
      - db
    networks:
      - michi_net

networks:
  michi_net:
    driver: bridge

volumes:
  mysql_data:
