version: "3.9"

services:
  web:
    build: .
    container_name: juegomichi_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=juegomichi.settings
    networks:
      - michi_net

networks:
  michi_net:
    driver: bridge
